language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

# command to install dependencies
install:
  - "pip install -e . --upgrade"
  - "pipenv install --dev --skip-lock"

# command to run tests
jobs:
  include:
    - stage: Style Tests ✨
      script: pipenv run flake8
    - stage: Main Test Suite ✨✨
      script: pipenv run pytest tests
