sudo: false
cache: pip
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TEST_SUITE='-m cli'
  - TEST_SUITE='-m install'
  - TEST_SUITE='-m run'
  - TEST_SUITE='-m dotvenv -m check -m unused'
  - TEST_SUITE='-m requirements'
  - TEST_SUITE='-m complex'
  - TEST_SUITE='-m project'
  - TEST_SUITE='-m utils'
  # - "pypy" # too many cache issues
  # - "3.7-dev"  # no need, slows down builds
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run pytest tests $TEST_SUITE"

# command to run tests
# jobs:
  # include:
    # - stage: "✨ Flake8 Nit–Picking ✨"
      # python: "3.6"
      # script: "pipenv run flake8"
