sudo: false
dist: trusty
cache: pip
language: python
python:
  - "3.6"
  - "2.7"
env:
  - TEST_SUITE='dotvenv or check or unused or requirements'
    CACHE_NAME='JOB1'
  - TEST_SUITE='complex'
    CACHE_NAME='JOB2'
  - TEST_SUITE='markers or run or project or utils'
    CACHE_NAME='JOB3'
  - TEST_SUITE='not (dotvenv or check or unused or requirements or complex or markers or run or project or utils or install)'
    CACHE_NAME='JOB4'
  - TEST_SUITE='install'
    CACHE_NAME='JOB5'

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - 'if [[ "$TEST_SUITE" == "install" ]]; then export PYTEST_ADDOPTS="--cache-clear"; fi'
  - "pipenv run bash ./run-tests.sh"

jobs:
  include:
    - stage: integration
      env: TEST_SUITE='cli'
    # - stage: takes-forever
    #   env:
    #     - TEST_SUITE='install'
    #     - PYTEST_ADDOPTS='--cache-clear'
    #     - RUN_INTEGRATION_TESTS=1

stages:
  - integration
  - test
  # - name: takes-forever
  #   if: branch = master
