sudo: false
cache: pip
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TEST_SUITE='cli'
  - TEST_SUITE='not cli'
  # - "pypy" # too many cache issues
  # - "3.7-dev"  # no need, slows down builds
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-stragetgy=only-if-needed"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run pytest tests -m $TEST_SUITE"

# command to run tests
# jobs:
  # include:
    # - stage: "✨ Flake8 Nit–Picking ✨"
      # python: "3.6"
      # script: "pipenv run flake8"
